spring.application.name=freezer

# H2
spring.datasource.url=${DB_URL:jdbc:h2:file:./freezer-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver

# Initialize schema.sql for the embedded database
spring.sql.init.mode=always
