CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT PRIMARY KEY,
    monthly_budget INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shopping_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fridge_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL DEFAULT 0,
    purchased_on DATE NOT NULL,
    expires_on DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    payload_json CLOB NOT NULL,
    saved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fridge_items_expires_on
    ON fridge_items (expires_on);

CREATE INDEX IF NOT EXISTS idx_fridge_items_purchased_on
    ON fridge_items (purchased_on);

MERGE INTO app_settings (id, monthly_budget, created_at, updated_at)
KEY (id)
VALUES (1, 30000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
